#passwords=['$2b$12$Kt8MScKPe4wWyB1CPEIJTeWngA8u4X1Vq1mL.XFjfHIELutuBC2wi', '$2b$12$q1D6sp5x3rs5rZUOa4yo.Oet04ItNGbWvPClxyoq5AEaau5s23tma']

credentials:
  usernames:
    shreya:
      email: rshrey1947@gmail.com
      name: Shreya Mandi
      password: $2b$12$Kt8MScKPe4wWyB1CPEIJTeWngA8u4X1Vq1mL.XFjfHIELutuBC2wi
    suhas:
      email: 4suhask@gmail.com
      name: Suhas K
      password: '$2b$12$q1D6sp5x3rs5rZUOa4yo.Oet04ItNGbWvPClxyoq5AEaau5s23tma'
cookie:
  expiry_days: 0
  key: abcd
  name: cookie_monster
preauthorised:
  emails:
    - shreya.mandi11@gmail.com